#!/bin/sh
rsync -av ./ --exclude 'rsyncfile' --exclude 'rss/' --exclude 'db/' --exclude '.git/' --exclude 'cookie_*' --exclude '*.csv' --exclude '*.swp' --exclude '*.log' erminn.sakura.ne.jp:www/2coch/

